package com.htp.controller;


import com.htp.controller.requests.RoleCreateRequest;
import com.htp.domain.Role;
import com.htp.repository.RoleDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@CrossOrigin
@RequestMapping(value = "/rest/roles")
public class RoleController {
    @Autowired
    private RoleDao roleDao;

    @PostMapping
    @Transactional
    @ResponseStatus(HttpStatus.CREATED)
    public ResponseEntity<Role> createRole(@RequestBody RoleCreateRequest request) {
        Role role = new Role();
        //roleId is empty - will be generated by DB
        role.setNameRole(request.getNameRole());
        role.setRoleType(request.getRoleType());

        Role savedRole = roleDao.save(role);

        return new ResponseEntity<>(savedRole, HttpStatus.OK);
    }

    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<List<Role>> getRoles() {
        return new ResponseEntity<>(roleDao.findAll(), HttpStatus.OK);
    }

}
